export default [
    {
        id: 1,
        img1: require('../assets/fries1.png'),
        img2: require('../assets/fries.png'),
        name: 'FRIES',
        price: 4,
        translateY: [60, -60, 60],
        rotate: ['-21.06deg', '0deg', '-21.06deg'],
    },
    {
        id: 2,
        img1: require('../assets/coffee1.png'),
        img2: require('../assets/coffee2.png'),
        name: 'LATTE',
        price: 3,
        translateY: [-65, -65, -65],
        scale: [0, 1, 0],
        rotate: ['0deg', '21.06deg', '0deg'],
        opacity: [0, 1, 0],
    },
    {
        id: 3,
        img1: require('../assets/burger1.png'),
        img2: require('../assets/burger2.png'),
        name: 'BURGER',
        price: 6,
        translateY: [0, -50, 0],
    },
];
